# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=crittersandcompanions
mod_name=Critters and Companions
mod_author=Joosh, EterDelta
mod_version=1.21.1-0.0.0-dev
mod_description=Critters and Companions is a vanilla-style creature mod which fills the overworld with new animals.
release_type=release

# Common
mc_version=1.21.1

# Parchment
parchment_version=2024.11.17

# Neoforge
neoforge_version=21.1.152

# Fabric
fabric_api_version=0.115.1+1.21.1
fabric_loader_version=0.16.10

# Dependencies
geckolib_version=4.7.5.1
porting_lib_version=3.1.0-beta.75
forge_config_port_version=21.1.3
curios_version=9.5.1+1.21.1
trinkets_version=3.10.0
mixin_extras_version=0.4.1
pathfinding_renderer_version=1.1.0
jade_version=iku9fmp8

jei_version=19.21.0.247
easy_villager_version=O3M0Xv8Q

# Publishing
maven_group=dev.bonsai-studios
modrinth_project_id=Yd4wb5wZ
curseforge_project_id=574913