# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_id = crittersandcompanions
mod_name = Critters and Companions
mod_version = 2.6.1
mod_description = Critters and Companions is a vanilla-style creature mod which fills the overworld with new animals.
maven_group = io.github.bonsaistudi0s.crittersandcompanions
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
architectury_api_version = 9.2.14
fabric_loader_version = 0.19.3
fabric_api_version = 0.92.9+1.20.1
forge_version = 1.20.1-47.4.10
parchment_version = 2023.09.03
geckolib_version = 4.2.3
porting_lib_version = 2.3.16-beta.81+1.20.1
curios_version = 5.14.1+1.20.1
trinkets_version = 3.7.1
yacl_version = 3.6.1+1.20.1
yacl_version_short = 3.6.1
modmenu_version = 7.2.2
jade_version = 11.12.3