# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>0.0.0-dev</version>
#    <timestamp>2026-06-24T20:12:28.874Z</timestamp>
#    <hash>80a1c9ad60219c1f</hash>
# </meta>

name: Bug Report
description: File a bug report
labels: ["bug"]

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: loader
    attributes:
      label: Loader
      multiple: false
      options:
        - "neoforge"
        - "fabric"
        - "forge"
    validations:
      required: true

  - type: input
    id: version-version
    attributes:
      label: Mod Version
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      multiple: false
      options:
        - "1.21"
        - "1.20"
        - "1.19"
        - "1.18"
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: log output
      description: Please copy and paste your log output to https://mclo.gs/ or a similar site and paste the link here.
