# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>0.0.0-dev</version>
#    <timestamp>2026-06-24T20:12:28.874Z</timestamp>
#    <hash>50bdd3d142fbd99f</hash>
# </meta>

blank_issues_enabled: false
