modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
authors = "${mod_author}"
description = "${mod_description}"
updateJSONURL = 'https://api.modrinth.com/updates/critters-and-companions/forge_updates.json?neoforge=only'

[[dependencies.${mod_id}]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config="${mod_id}.mixins.json"