name: Release
on:
   release:
      types: [published]

env:
   CI: true

jobs:
   build:
      runs-on: ubuntu-latest
      timeout-minutes: 20
      permissions:
         contents: read
         packages: write
      steps:
         - uses: actions/checkout@v4
           with:
              lfs: true

         - uses: actions/setup-java@v4
           with:
              java-version: 21
              distribution: temurin

         - name: Setup Gradle
           uses: gradle/actions/setup-gradle@v4

         - name: Build and upload
           uses: gradle/gradle-build-action@v2
           with:
              arguments: build curseforge modrinth publish
           env:
              MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
              CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
              CHANGELOG: ${{ github.event.release.body }}
              RELEASE_VERSION: ${{ github.event.release.tag_name }}
