# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>0.0.0-dev</version>
#    <timestamp>2026-06-24T20:12:28.874Z</timestamp>
#    <hash>b827464d2135f4f8</hash>
# </meta>

name: Test

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize]

  push:
    branches:
      - "main"
      - "main/**"

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: 26
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          dependency-graph: generate-and-submit

      - uses: PssbleTrngle/find-release@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: action
        with:
          type: draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: ./gradlew build check --stacktrace
        env:
          RELEASE_VERSION: ${{ steps.action.outputs.tag }}

      - name: Publish -SNAPSHOT version
        if: ${{ fromJSON(steps.action.outputs.matched) }}
        run: ./gradlew publish
        continue-on-error: true
        env:
          RELEASE_VERSION: ${{ steps.action.outputs.tag }}
          SNAPSHOT: true
